// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: plugin/plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Plugin_RegisterListener_FullMethodName = "/plugin.Plugin/RegisterListener"
	Plugin_RegisterCmd_FullMethodName      = "/plugin.Plugin/RegisterCmd"
	Plugin_SendMessage_FullMethodName      = "/plugin.Plugin/SendMessage"
)

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginClient interface {
	// Events are implemented through a stream that is held open
	RegisterListener(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListenerClientData, Event], error)
	RegisterCmd(ctx context.Context, in *CmdDef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CmdInvocation], error)
	// Commands a plugin can call
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageRes, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) RegisterListener(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListenerClientData, Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plugin_ServiceDesc.Streams[0], Plugin_RegisterListener_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListenerClientData, Event]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_RegisterListenerClient = grpc.BidiStreamingClient[ListenerClientData, Event]

func (c *pluginClient) RegisterCmd(ctx context.Context, in *CmdDef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CmdInvocation], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Plugin_ServiceDesc.Streams[1], Plugin_RegisterCmd_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CmdDef, CmdInvocation]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_RegisterCmdClient = grpc.ServerStreamingClient[CmdInvocation]

func (c *pluginClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageRes)
	err := c.cc.Invoke(ctx, Plugin_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServer is the server API for Plugin service.
// All implementations must embed UnimplementedPluginServer
// for forward compatibility.
type PluginServer interface {
	// Events are implemented through a stream that is held open
	RegisterListener(grpc.BidiStreamingServer[ListenerClientData, Event]) error
	RegisterCmd(*CmdDef, grpc.ServerStreamingServer[CmdInvocation]) error
	// Commands a plugin can call
	SendMessage(context.Context, *Message) (*MessageRes, error)
	mustEmbedUnimplementedPluginServer()
}

// UnimplementedPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServer struct{}

func (UnimplementedPluginServer) RegisterListener(grpc.BidiStreamingServer[ListenerClientData, Event]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterListener not implemented")
}
func (UnimplementedPluginServer) RegisterCmd(*CmdDef, grpc.ServerStreamingServer[CmdInvocation]) error {
	return status.Errorf(codes.Unimplemented, "method RegisterCmd not implemented")
}
func (UnimplementedPluginServer) SendMessage(context.Context, *Message) (*MessageRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedPluginServer) mustEmbedUnimplementedPluginServer() {}
func (UnimplementedPluginServer) testEmbeddedByValue()                {}

// UnsafePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServer will
// result in compilation errors.
type UnsafePluginServer interface {
	mustEmbedUnimplementedPluginServer()
}

func RegisterPluginServer(s grpc.ServiceRegistrar, srv PluginServer) {
	// If the following call pancis, it indicates UnimplementedPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Plugin_ServiceDesc, srv)
}

func _Plugin_RegisterListener_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginServer).RegisterListener(&grpc.GenericServerStream[ListenerClientData, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_RegisterListenerServer = grpc.BidiStreamingServer[ListenerClientData, Event]

func _Plugin_RegisterCmd_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CmdDef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServer).RegisterCmd(m, &grpc.GenericServerStream[CmdDef, CmdInvocation]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Plugin_RegisterCmdServer = grpc.ServerStreamingServer[CmdInvocation]

func _Plugin_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Plugin_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// Plugin_ServiceDesc is the grpc.ServiceDesc for Plugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Plugin_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterListener",
			Handler:       _Plugin_RegisterListener_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RegisterCmd",
			Handler:       _Plugin_RegisterCmd_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin/plugin.proto",
}
